import { createPlugin } from "@aionima/sdk";

export default createPlugin({
  async activate(api) {
    api.registerStack({
      id: "stack-fancy-ui",
      label: "Fancy UI",
      description:
        "Preferred UI component libraries for Aionima projects: react-fancy (layout, controls, dialogs), " +
        "fancy-code (code editor), fancy-sheets (spreadsheet/data grid), react-echarts (charts). " +
        "All built on Tailwind CSS with Catppuccin theme support.",
      category: "tooling",
      projectCategories: ["app", "web"],
      requirements: [
        { id: "react-fancy", label: "@particle-academy/react-fancy", type: "provided" },
        { id: "fancy-code", label: "@particle-academy/fancy-code", type: "provided" },
        { id: "fancy-sheets", label: "@particle-academy/fancy-sheets", type: "provided" },
        { id: "react-echarts", label: "@particle-academy/react-echarts", type: "provided" },
      ],
      installActions: [
        {
          id: "npm.install.fancy",
          label: "Install Fancy UI packages",
          command:
            "npm install @particle-academy/react-fancy @particle-academy/fancy-code @particle-academy/fancy-sheets @particle-academy/react-echarts",
        },
      ],
      guides: [
        {
          title: "Component Reference",
          content: [
            "# Fancy UI Components",
            "",
            "## @particle-academy/react-fancy",
            "",
            "### Layout",
            "- `<Sidebar>` — collapsible sidebar with icon-only mode",
            "  - `<Sidebar.Group label=\"Section\">` — navigation group",
            "  - `<Sidebar.Item active icon={<Icon />} onClick={fn}>Label</Sidebar.Item>`",
            "  - `<Sidebar.Toggle />` — collapse/expand button",
            "- `<MobileMenu.Flyout open side=\"left\" title=\"Title\" onClose={fn}>` — mobile drawer",
            "  - `<MobileMenu.Item active icon={<Icon />} onClick={fn}>Label</MobileMenu.Item>`",
            "",
            "### Controls",
            "- `<MultiSwitch value onValueChange list={[{value, label}]} />` — segmented toggle",
            "- `<Button variant=\"default|outline|ghost\" size=\"sm|md|lg\">` — styled button",
            "- `<Badge variant=\"default|secondary|outline\">` — status/tag badge",
            "- `<Input>` — text input",
            "- `<Card className>` — content card container",
            "",
            "### Dialogs",
            "- `<Dialog open onOpenChange={fn}>` — modal container",
            "  - `<DialogContent className>` — dialog body (auto-centers, backdrop)",
            "  - `<DialogHeader>`, `<DialogTitle>`, `<DialogDescription>`",
            "  - `<DialogFooter>` — bottom action bar",
            "",
            "### Utilities",
            "- `cn(...classes)` — Tailwind-safe class merging (import from `@/lib/utils`)",
            "- `useToast()` — toast notification hook",
            "- `<PageScroll>` — full-height scrollable wrapper",
            "",
            "## @particle-academy/fancy-code",
            "",
            "```tsx",
            "import { FancyCode } from '@particle-academy/fancy-code';",
            "",
            "<FancyCode",
            "  value={code}",
            "  onChange={setCode}",
            "  language=\"javascript\" // or python, json, markdown, etc.",
            "  readonly={false}",
            "/>",
            "```",
            "",
            "## @particle-academy/fancy-sheets",
            "",
            "```tsx",
            "import { FancySheets } from '@particle-academy/fancy-sheets';",
            "",
            "<FancySheets",
            "  data={[",
            "    { name: 'Row 1', value: 42 },",
            "    { name: 'Row 2', value: 73 },",
            "  ]}",
            "  columns={[",
            "    { key: 'name', header: 'Name' },",
            "    { key: 'value', header: 'Value', type: 'number' },",
            "  ]}",
            "  onCellChange={(row, col, value) => { ... }}",
            "/>",
            "```",
            "",
            "## @particle-academy/react-echarts",
            "",
            "```tsx",
            "import { EChart } from '@particle-academy/react-echarts';",
            "",
            "// Line chart",
            "<EChart option={{",
            "  xAxis: { type: 'category', data: ['Mon', 'Tue', 'Wed'] },",
            "  yAxis: { type: 'value' },",
            "  series: [{ type: 'line', data: [150, 230, 224] }],",
            "}} />",
            "",
            "// Candlestick chart (financial)",
            "<EChart option={{",
            "  xAxis: { type: 'category', data: dates },",
            "  yAxis: { type: 'value' },",
            "  series: [{",
            "    type: 'candlestick',",
            "    data: ohlcData, // [[open, close, low, high], ...]",
            "  }],",
            "}} />",
            "```",
            "",
            "## Styling",
            "",
            "All components use Tailwind CSS 4 with Catppuccin theme:",
            "- Text: `text-foreground`, `text-muted-foreground`, `text-subtext0`",
            "- Backgrounds: `bg-card`, `bg-surface0`, `bg-mantle`, `bg-base`",
            "- Borders: `border-border`",
            "- Colors: `text-green`, `text-red`, `text-yellow`, `text-blue`",
            "- Sizing: `text-[13px]` body, `text-[11px]` secondary, `text-[10px]` badges",
            "",
            "## Do NOT Use",
            "- Material UI, Chakra UI, Ant Design, shadcn/ui",
            "- Chart.js, Recharts — use react-echarts",
            "- Raw HTML tables — use fancy-sheets",
            "- Custom sidebar/navigation — use react-fancy Sidebar",
          ].join("\n"),
        },
      ],
      tools: [
        {
          id: "fancy-install",
          label: "Install Fancy UI",
          description: "Install all Fancy UI packages",
          action: "shell",
          command:
            "npm install @particle-academy/react-fancy @particle-academy/fancy-code @particle-academy/fancy-sheets @particle-academy/react-echarts",
        },
      ],
      icon: "sparkles",
    });

    // Register knowledge namespace so docs appear in the Docs page
    api.registerKnowledge({
      id: "fancy-ui",
      label: "Fancy UI",
      description: "Component library reference for react-fancy, fancy-code, fancy-sheets, react-echarts",
      contentDir: new URL("../docs", import.meta.url).pathname,
      topics: [
        { path: "components.md", title: "Component Reference" },
      ],
    });
  },
});
